apiVersion: v1
kind: Pod
metadata:
  name: ngkore-private-reg
spec:
  containers:
  - name: ngk-amf
    image: ngkore/ngk-amf:1.0
  - name: ngk-pod-init
    image: ngkore/ngk-pod-init:1.0
  - name: ngk-nrf
    image: ngkore/ngk-nrf:1.0
  - name: ngk-smf
    image: ngkore/ngk-smf:1.0
  - name: ngk-ausf
    image: ngkore/ngk-ausf:1.0
  - name: ngk-nssf
    image: ngkore/ngk-nssf:1.0
  - name: ngk-pcf
    image: ngkore/ngk-pcf:1.0
  - name: ngk-udr
    image: ngkore/ngk-udr:1.0
  - name: ngk-udm
    image: ngkore/ngk-udm:1.0
  - name: ngk-webui
    image: ngkore/ngk-webui:1.0
  - name: ngk-sctplb
    image: ngkore/ngk-sctplb:1.0
  - name: ngk-metricfunc
    image: ngkore/ngk-metricfunc:1.0
  - name: ngk-upf-epc-bess
    image: ngkore/ngk-upf-epc-bess:1.0
  - name: ngk-upf-epc-pfcpiface
    image: ngkore/ngk-upf-epc-pfcpiface:1.0
  - name: ngk-simapp
    image: ngkore/ngk-simapp:1.0
  imagePullSecrets:
  - name: regcred

