# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

# Default values for all SD-CORE Helm charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Images tagged for the release
omec-control-plane:
  enable4G: false
  #images:
  #  tags:
      #4G control Plane images
  #config:
  #  config4g:
  #    deploy: true

omec-user-plane:
  enable: true
  images:
    tags:
      bess: "ngkore/ngk-upf-epc-bess:1.0"
      pfcpiface: "ngkore/ngk-upf-epc-pfcpiface:1.0"
  #images:
  #  tags:
      #4G/5G user plane images
  #config:
  #  upf:
  #    cfgFiles:
  #      upf.json:
  #        cpiface:

omec-sub-provision:
  enable: true
  #images:
  #  tags:
  images:
    tags:
      init: ngkore/ngk-pod-init:1.0
      simapp: ngkore/ngk-simapp:1.0

5g-control-plane:
  enable5G: true
  kafka:
    deploy: false
    persistence:
      enabled: false
    zookeeper:
      persistence:
        enabled: false
  #images:
  #  tags:
      #5G NF images
  images:
    tags:
      init: ngkore/ngk-pod-init:1.0
      nrf: ngkore/ngk-nrf:1.0
      amf: ngkore/ngk-amf:1.0
      smf: ngkore/ngk-smf:1.0
      ausf: ngkore/ngk-ausf:1.0
      nssf: ngkore/ngk-nssf:1.0
      pcf: ngkore/ngk-pcf:1.0
      udr: ngkore/ngk-udr:1.0
      udm: ngkore/ngk-udm:1.0
      webui: ngkore/ngk-webui:1.0
      sctplb: ngkore/ngk-sctplb:1.0
      metricfunc: ngkore/ngk-metricfunc:1.0
      upfadapter: ngkore/ngk-smf:1.0

5g-ran-sim:
  enable: false
  #images:
  #  tags:
      #RAN SIM image
